services:
  - type: web
    name: mothra
    runtime: python
    rootDir: landing-page
    buildCommand: > 
      npm install && npm run build && 
      pip install -r scripts/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    workingDir: scripts
    envVars:
      - key: MOTHRA_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mothra-DATABASE_URL
          property: connectionString

databases:
  - name: mothra-databases
    databaseName: mothra
    plan: free