apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic
  namespace: mothra
  labels:
    app: ic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic
  template:
    metadata:
      labels:
        app: ic
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: ic
          image: ghcr.io/ddmal/mothra-ic:sha-6bf1c19
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ic
  namespace: mothra
  labels:
    app: ic
spec:
  selector:
    app: ic
  ports:
    - name: http
      port: 8000
      targetPort: 8000
