apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mothra-stored-models
  namespace: mothra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mothra-stored-models-pv
  resources:
    requests:
      storage: 200Gi
